# Generated by Django 3.0.6 on 2021-07-09 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('allergy', models.CharField(max_length=50)),
                ('major_operation', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 9, 22, 13, 33, 817351))),
            ],
        ),
    ]
