# Generated by Django 3.1.7 on 2021-07-11 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210711_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 10, 53, 18, 989514)),
        ),
        migrations.AlterField(
            model_name='add',
            name='user_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
