# Generated by Django 3.1.7 on 2021-07-11 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210711_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 10, 54, 28, 820995)),
        ),
        migrations.AlterField(
            model_name='add',
            name='user_file',
            field=models.ImageField(default='default.jpg', upload_to='xyz'),
        ),
    ]
